env:
  browser: true
  es2021: true
extends: plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: "off"
